# Generated by Django 6.0.7 on 2026-09-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='receive_whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
