# Generated by Django 6.0.7 on 2026-09-29 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_parent_receive_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], max_length=10)),
                ('old_status', models.CharField(blank=True, max_length=10)),
                ('new_status', models.CharField(blank=True, max_length=10)),
                ('subject_name', models.CharField(blank=True, max_length=100)),
                ('period_number', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='attendance.attendance')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_changes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='attendance.student')),
            ],
            options={
                'verbose_name': 'Attendance Audit Log',
                'verbose_name_plural': 'Attendance Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
